### ISSUE TITLE
Missing error message and associated trouble shooting steps

### ISSUE THREAD

**Issue by XcoderBlood** [MicrosoftDocs/azure-media-services#9]
Getting error message back from Media Services v3 message starts with "This value is not valid for H.264 level 'auto' as it results in an invalid frame resolution as defined by the" and lists the height and width of the video output size we want.

I cannot find in any of the documentation this error message. I cannot find in any of the documentation what the rules are for video output sizes.

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 513d6025-57d9-7441-4f0c-dcd6670784aa
* Version Independent ID: 513d6025-57d9-7441-4f0c-dcd6670784aa
* Content: [Troubleshoot Media Services](https://learn.microsoft.com/en-us/azure/media-services/latest/troubleshooting)
* Content Source: [media-services/latest/troubleshooting.md](https://github.com/MicrosoftDocs/azure-media-services/blob/main/media-services/latest/troubleshooting.md)
* Service: **media-services**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by IngridAtMicrosoft** [comment]
Hello @XcoderBlood,
I have contacted support and this is what they suggest:

This might just be a resolution size issue.  There are two basic rules for sizing for choosing a group of resolutions.  1) The aspect ratio must be maintained between different resolutions. 2) Both the width and height values must be divisible by 2 (even).  This significantly reduces the number of resolution steps that can be made in a Transform.

For example, let’s say you want to start with a resolution of 720p and then step up slightly from there.  That width and height is 1080 x 720.  You can’t just add 1 to each because it’d break both rules, so add 2.  1082 x 722 has a ratio of ~1.775, but we need to keep that at 1.777_(repeating) which is also 16:9.

If this doesn't solve your problem, please open a support ticket.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
@XcoderBlood Please close this issue.
